apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
      nodePort: 31008
  type: NodePort
